export const INDIA_LOCATIONS = [
  { state: "West Bengal", cities: ["Kolkata", "Siliguri", "Asansol", "Durgapur", "Darjeeling", "Howrah", "Kharagpur", "Haldia", "Malda"] },
  { state: "Maharashtra", cities: ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik", "Aurangabad", "Navi Mumbai", "Solapur"] },
  { state: "Delhi", cities: ["New Delhi", "North Delhi", "South Delhi", "Dwarka"] },
  { state: "Karnataka", cities: ["Bengaluru", "Mysuru", "Hubli", "Mangaluru", "Belagavi", "Davangere", "Ballari"] },
  { state: "Tamil Nadu", cities: ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli", "Vellore"] },
  { state: "Uttar Pradesh", cities: ["Lucknow", "Kanpur", "Ghaziabad", "Agra", "Varanasi", "Meerut", "Noida", "Prayagraj", "Bareilly"] },
  { state: "Gujarat", cities: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhinagar"] },
  { state: "Telangana", cities: ["Hyderabad", "Warangal", "Nizamabad", "Khammam", "Karimnagar"] },
  { state: "Rajasthan", cities: ["Jaipur", "Jodhpur", "Kota", "Bikaner", "Ajmer", "Udaipur", "Bhilwara", "Alwar"] },
  { state: "Kerala", cities: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Kannur"] },
  { state: "Punjab", cities: ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali"] },
  { state: "Haryana", cities: ["Faridabad", "Gurugram", "Panipat", "Ambala", "Rohtak", "Hisar", "Karnal"] },
  { state: "Madhya Pradesh", cities: ["Indore", "Bhopal", "Jabalpur", "Gwalior", "Ujjain", "Sagar", "Rewa"] },
  { state: "Bihar", cities: ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia", "Darbhanga", "Arrah"] },
  { state: "Andhra Pradesh", cities: ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Rajahmundry", "Tirupati"] },
  { state: "Assam", cities: ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Tinsukia", "Tezpur"] },
  { state: "Odisha", cities: ["Bhubaneswar", "Cuttack", "Rourkela", "Brahmapur", "Sambalpur", "Puri"] },
  { state: "Chhattisgarh", cities: ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg", "Rajnandgaon"] },
  { state: "Jharkhand", cities: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar", "Hazaribagh"] },
  { state: "Uttarakhand", cities: ["Dehradun", "Haridwar", "Roorkee", "Haldwani", "Rudrapur", "Rishikesh"] },
  { state: "Himachal Pradesh", cities: ["Shimla", "Dharamshala", "Mandi", "Solan", "Kullu", "Manali"] },
  { state: "Goa", cities: ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda"] },
  { state: "Tripura", cities: ["Agartala", "Dharmanagar", "Udaipur"] },
  { state: "Meghalaya", cities: ["Shillong", "Tura", "Nongstoin"] },
  { state: "Manipur", cities: ["Imphal", "Thoubal", "Kakching"] },
  { state: "Nagaland", cities: ["Dimapur", "Kohima", "Mokokchung"] },
  { state: "Arunachal Pradesh", cities: ["Itanagar", "Naharlagun", "Pasighat"] },
  { state: "Mizoram", cities: ["Aizawl", "Lunglei", "Saiha"] },
  { state: "Sikkim", cities: ["Gangtok", "Namchi", "Gyalshing", "Mangan"] },
  { state: "Andaman and Nicobar Islands", cities: ["Port Blair"] },
  { state: "Chandigarh", cities: ["Chandigarh"] },
  { state: "Puducherry", cities: ["Puducherry", "Ozhukarai", "Karaikal"] }
];

export const FLAT_LOCATIONS = INDIA_LOCATIONS.flatMap(s => s.cities.map(c => `${c}, ${s.state}`));
