import type { WeatherCondition } from '../weather'

export type SuggestionItem = {
  text: string
  weather: WeatherCondition[]
  time: ('morning' | 'afternoon' | 'evening' | 'night')[]
  season: ('summer' | 'monsoon' | 'winter' | 'any')[]
  region: ('hills' | 'metro' | 'coastal' | 'college' | 'any')[]
  dayType: ('weekday' | 'weekend' | 'any')[]
  vibe: 'move' | 'create' | 'hang' | 'learn' | 'explore'
}

const w = (...c: WeatherCondition[]): WeatherCondition[] => c
const ANY_W: WeatherCondition[] = ['sunny','partly_cloudy','cloudy','foggy','drizzle','rainy','thunderstorm','snow','windy']

export const SUGGESTION_POOL: SuggestionItem[] = [
  // ── SUNNY (40) ──────────────────────────────────────────────────────────────
  { text: 'Sundowner walk at the lake', weather: w('sunny'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Cricket on the gully', weather: w('sunny','partly_cloudy'), time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Rooftop chai as the sun sets', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Morning run with the squad', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Open-air yoga session', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['winter','summer'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Frisbee on the maidan', weather: w('sunny'), time: ['afternoon','evening'], season: ['winter','summer'], region: ['any'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Cycle to the viewpoint and back', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['any'], region: ['hills','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Picnic by the river with dabba', weather: w('sunny'), time: ['afternoon'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Trek to the hilltop + maggi at top', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['winter','summer'], region: ['hills','any'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Kite flying on the terrace', weather: w('sunny','windy'), time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Garden walk with filter coffee', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Sunrise point gathering', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['hills','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Football in the park', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['winter','summer'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Evening jam at the amphitheatre', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['winter'], region: ['metro','any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Botanical garden stroll', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Photography walk in the old city', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['winter'], region: ['metro','any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Rooftop book club with chai', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'learn' },
  { text: 'Evening cricket with snacks', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Sunset watchers at the bridge', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Morning birding walk', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Breakfast cycling group', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Open-air painting session', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Riverside picnic with games', weather: w('sunny'), time: ['afternoon'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Morning meditation circle outside', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Terrace dance practice', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Open mic in the garden', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['winter'], region: ['metro','any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Hammock hang at the park', weather: w('sunny'), time: ['afternoon'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Badminton under the open sky', weather: w('sunny','partly_cloudy'), time: ['morning','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Street food walk at golden hour', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Swimming pool session', weather: w('sunny'), time: ['afternoon'], season: ['summer'], region: ['metro','any'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Heritage walk with headphones', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['winter'], region: ['metro','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Sunset volleyball game', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['any'], region: ['coastal','any'], dayType: ['any'], vibe: 'move' },
  { text: 'Rooftop BBQ gathering', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['winter'], region: ['metro','any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Community clean-up drive + chai', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Skateboard at the plaza', weather: w('sunny'), time: ['afternoon','evening'], season: ['any'], region: ['metro','any'], dayType: ['any'], vibe: 'move' },
  { text: 'Terrace stargazing with binoculars', weather: w('sunny'), time: ['night'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Kho-kho revival gathering', weather: w('sunny','partly_cloudy'), time: ['afternoon','evening'], season: ['any'], region: ['college','any'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Cycle polo attempt in the park', weather: w('sunny'), time: ['morning','afternoon'], season: ['winter'], region: ['metro','any'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Morning outdoor yoga + chai party', weather: w('sunny'), time: ['morning'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Photography golden hour run', weather: w('sunny'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'create' },

  // ── PARTLY CLOUDY (35) ──────────────────────────────────────────────────────
  { text: 'Chai pe charcha at the corner stall', weather: w('partly_cloudy','cloudy'), time: ['morning','afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Momo run after sunset', weather: w('partly_cloudy','cloudy'), time: ['evening','night'], season: ['winter'], region: ['hills','any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Photography walk in the bazaar', weather: w('partly_cloudy','cloudy'), time: ['morning','afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Terrace gossip session with chai', weather: w('partly_cloudy'), time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Nature journaling meetup', weather: w('partly_cloudy','cloudy'), time: ['morning','afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Dosa breakfast run', weather: w('partly_cloudy','sunny'), time: ['morning'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Walking food tour of the old town', weather: w('partly_cloudy','cloudy'), time: ['afternoon','evening'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Rooftop guitar circle', weather: w('partly_cloudy'), time: ['evening','night'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Evening café hop', weather: w('partly_cloudy','cloudy'), time: ['afternoon','evening'], season: ['any'], region: ['metro','any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Sketching in the market', weather: w('partly_cloudy'), time: ['morning','afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Street art appreciation walk', weather: w('partly_cloudy','cloudy'), time: ['afternoon'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Snack run to the mithai shop', weather: w('partly_cloudy','cloudy'), time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Evening Antakshari at the park', weather: w('partly_cloudy','cloudy'), time: ['evening'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Kachori and gossip circle', weather: w('partly_cloudy','cloudy'), time: ['morning','afternoon'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Thali lunch spot discovery run', weather: w('partly_cloudy','sunny'), time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Cloud watching circle at the park', weather: w('partly_cloudy','cloudy'), time: ['afternoon'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Bookstore hang with kulhad chai', weather: w('partly_cloudy','cloudy'), time: ['afternoon'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'learn' },
  { text: 'Comics and coffee hang', weather: w('partly_cloudy','cloudy'), time: ['afternoon'], season: ['any'], region: ['metro','college'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Chai and climate adda', weather: w('partly_cloudy','cloudy'), time: ['afternoon','evening'], season: ['any'], region: ['college','metro'], dayType: ['weekday'], vibe: 'learn' },
  { text: 'Carom on the terrace', weather: w('partly_cloudy','cloudy'), time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Ludo tournament outdoors', weather: w('partly_cloudy'), time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Newspaper reading adda with chai', weather: w('partly_cloudy','cloudy'), time: ['morning'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'learn' },
  { text: 'Nimbu paani adda watching the sky', weather: w('partly_cloudy'), time: ['afternoon'], season: ['summer'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Quick museum hop', weather: w('partly_cloudy','cloudy'), time: ['afternoon'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'learn' },
  { text: 'Sunset point selfie run', weather: w('partly_cloudy','sunny'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Evening momo + long chat', weather: w('partly_cloudy','cloudy'), time: ['evening'], season: ['winter'], region: ['hills','any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Light cooking class in the open', weather: w('partly_cloudy'), time: ['morning','afternoon'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Chai at the station platform', weather: w('partly_cloudy','cloudy'), time: ['morning','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Slow Sunday morning walk', weather: w('partly_cloudy','sunny'), time: ['morning'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Outdoor jam session with speakers', weather: w('partly_cloudy'), time: ['afternoon','evening'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Evening chai walk around the colony', weather: w('partly_cloudy','cloudy'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Vintage music listening session outdoor', weather: w('partly_cloudy'), time: ['afternoon','evening'], season: ['winter'], region: ['metro','any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Chaat run at 4pm sharp', weather: w('partly_cloudy','sunny'), time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Pav bhaji gathering on the terrace', weather: w('partly_cloudy','cloudy'), time: ['evening'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Terrace adda with nimbu paani', weather: w('partly_cloudy'), time: ['afternoon','evening'], season: ['summer'], region: ['any'], dayType: ['any'], vibe: 'hang' },

  // ── CLOUDY (30) ──────────────────────────────────────────────────────────────
  { text: 'Maggi night with the squad', weather: w('cloudy','rainy','drizzle'), time: ['evening','night'], season: ['monsoon','winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Filter coffee adda', weather: w('cloudy','drizzle'), time: ['morning','afternoon'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Indoor board game marathon', weather: w('cloudy','rainy'), time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Reading club at the café', weather: w('cloudy','drizzle'), time: ['afternoon'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'learn' },
  { text: 'Cooking together session', weather: w('cloudy','rainy'), time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Open mic at the café', weather: w('cloudy','drizzle'), time: ['evening'], season: ['any'], region: ['metro','college','any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Jazz café evening', weather: w('cloudy','drizzle'), time: ['evening'], season: ['any'], region: ['metro','any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Art class in the studio', weather: w('cloudy','rainy'), time: ['afternoon','evening'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Writing workshop at home', weather: w('cloudy','rainy'), time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Cozy brunch at the café', weather: w('cloudy','drizzle'), time: ['morning','afternoon'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Bookshelf swap session', weather: w('cloudy','rainy'), time: ['afternoon'], season: ['any'], region: ['college','metro','any'], dayType: ['weekend'], vibe: 'learn' },
  { text: 'DIY crafts afternoon', weather: w('cloudy','rainy'), time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Jam session in the music room', weather: w('cloudy','rainy'), time: ['afternoon','evening'], season: ['any'], region: ['college','any'], dayType: ['any'], vibe: 'create' },
  { text: 'Debate club chai session', weather: w('cloudy','drizzle'), time: ['afternoon','evening'], season: ['any'], region: ['college','metro'], dayType: ['weekday'], vibe: 'learn' },
  { text: 'Origami + tea hang', weather: w('cloudy','rainy'), time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Candlelit poetry reading', weather: w('cloudy','rainy'), time: ['evening','night'], season: ['winter','monsoon'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Home cooking challenge', weather: w('cloudy','rainy'), time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Indoor quiz night', weather: w('cloudy','rainy','thunderstorm'), time: ['evening','night'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Chai + Wordle competition', weather: w('cloudy','drizzle'), time: ['morning','afternoon'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Photography editing circle', weather: w('cloudy','rainy'), time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'DSLR basics workshop', weather: w('cloudy','rainy'), time: ['afternoon'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'learn' },
  { text: 'Vintage vinyl listening party', weather: w('cloudy','rainy'), time: ['afternoon','evening'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Café-hop on the slow street', weather: w('cloudy','drizzle'), time: ['afternoon'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Podcast recording circle', weather: w('cloudy','rainy'), time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Gentle yoga + chai indoors', weather: w('cloudy','drizzle'), time: ['morning','afternoon'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Indoor plant shop tour', weather: w('cloudy','drizzle'), time: ['afternoon'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Architecture walk in the city', weather: w('cloudy','partly_cloudy'), time: ['morning','afternoon'], season: ['winter'], region: ['metro','any'], dayType: ['weekend'], vibe: 'learn' },
  { text: 'Slow cooking Sunday session', weather: w('cloudy','rainy'), time: ['morning','afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Newspaper + chai + long conversation', weather: w('cloudy','drizzle'), time: ['morning'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Indoor pottery class', weather: w('cloudy','rainy'), time: ['afternoon'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'create' },

  // ── RAINY (30) ──────────────────────────────────────────────────────────────
  { text: 'Chai pakora party', weather: w('rainy','drizzle'), time: ['afternoon','evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Hot soup and gossip session', weather: w('rainy','drizzle'), time: ['evening'], season: ['monsoon','winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Movie night with blankets and snacks', weather: w('rainy','thunderstorm'), time: ['evening','night'], season: ['monsoon','winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Indoor cooking with rain soundtrack', weather: w('rainy','thunderstorm'), time: ['afternoon','evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Cozy chai circle with candles', weather: w('rainy','thunderstorm'), time: ['evening'], season: ['monsoon','winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Samosa + chai + cards gathering', weather: w('rainy','drizzle'), time: ['afternoon','evening'], season: ['monsoon','winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Rain watching from the window café', weather: w('rainy','drizzle'), time: ['afternoon','evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Board games all evening', weather: w('rainy','thunderstorm','cloudy'), time: ['afternoon','evening','night'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Hot chocolate movie night', weather: w('rainy','thunderstorm'), time: ['evening','night'], season: ['monsoon','winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Khichdi cook-off', weather: w('rainy','thunderstorm'), time: ['afternoon','evening'], season: ['monsoon','winter'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Rain photography run', weather: w('rainy','drizzle'), time: ['afternoon'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Monsoon music playlist swap', weather: w('rainy','drizzle'), time: ['evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Monsoon horror movie marathon', weather: w('rainy','thunderstorm'), time: ['evening','night'], season: ['monsoon'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Journaling session with chai in the rain', weather: w('rainy','drizzle'), time: ['afternoon','evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Comfort food potluck', weather: w('rainy','cloudy'), time: ['afternoon','evening'], season: ['monsoon','winter'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Rain poetry reading session', weather: w('rainy','drizzle'), time: ['afternoon','evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Warm maggi + ghost stories', weather: w('rainy','thunderstorm'), time: ['night'], season: ['monsoon','winter'], region: ['hills','any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Chai + Ludo marathon', weather: w('rainy','cloudy'), time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Netflix queue swap and watch together', weather: w('rainy','thunderstorm'), time: ['afternoon','evening','night'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Kashmiri chai gathering', weather: w('rainy','foggy'), time: ['evening'], season: ['winter','monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Homemade biryani together', weather: w('rainy','cloudy'), time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Monsoon adda with bhajans', weather: w('rainy','drizzle'), time: ['evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Hot idli sambar + gossip session', weather: w('rainy','drizzle'), time: ['morning','afternoon'], season: ['monsoon','winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Baingan bharta party at home', weather: w('rainy','cloudy'), time: ['afternoon','evening'], season: ['monsoon'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Cozy trivia night', weather: w('rainy','thunderstorm'), time: ['evening','night'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Instaprint photo swap + rainy adda', weather: w('rainy','drizzle'), time: ['afternoon'], season: ['monsoon'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Rainy day gratitude journaling', weather: w('rainy','drizzle'), time: ['morning','afternoon'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Cold brew attempt + rain viewing', weather: w('rainy','drizzle'), time: ['afternoon'], season: ['monsoon','summer'], region: ['metro','college'], dayType: ['any'], vibe: 'create' },
  { text: 'Reading books in silence together', weather: w('rainy','thunderstorm'), time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'learn' },
  { text: 'Dal chawal + old Hindi songs adda', weather: w('rainy','cloudy'), time: ['evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },

  // ── DRIZZLE (20) ──────────────────────────────────────────────────────────────
  { text: 'Drizzle walk with boots and chai', weather: w('drizzle'), time: ['morning','evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Quick café run before it pours', weather: w('drizzle','rainy'), time: ['afternoon'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Light rain photography session', weather: w('drizzle'), time: ['afternoon'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Cozy bookshop afternoon', weather: w('drizzle','cloudy'), time: ['afternoon'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'learn' },
  { text: 'Drizzly momo run in the lane', weather: w('drizzle','rainy'), time: ['evening'], season: ['monsoon','winter'], region: ['hills','any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Indoor music session with open windows', weather: w('drizzle'), time: ['afternoon','evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Warm upma brunch circle', weather: w('drizzle','cloudy'), time: ['morning'], season: ['monsoon','winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'First chai of the rain season', weather: w('drizzle','rainy'), time: ['afternoon','evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Dim sum + drizzle afternoon', weather: w('drizzle','cloudy'), time: ['afternoon'], season: ['monsoon'], region: ['metro','any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Drizzle + terrace + chai', weather: w('drizzle'), time: ['afternoon','evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Rain smell walk around the colony', weather: w('drizzle'), time: ['morning','evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Damp day baking gathering', weather: w('drizzle','cloudy'), time: ['afternoon'], season: ['monsoon'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Café sketching with windows open', weather: w('drizzle','cloudy'), time: ['afternoon'], season: ['monsoon'], region: ['metro','any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Drizzle Sunday brunch', weather: w('drizzle','cloudy'), time: ['morning'], season: ['monsoon'], region: ['metro','any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Poha breakfast in the drizzle', weather: w('drizzle'), time: ['morning'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Kanda poha + rain adda', weather: w('drizzle','rainy'), time: ['morning'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Museum hop on a damp day', weather: w('drizzle','cloudy'), time: ['afternoon'], season: ['monsoon'], region: ['metro','any'], dayType: ['weekend'], vibe: 'learn' },
  { text: 'Slow walk in the old town', weather: w('drizzle','cloudy'), time: ['morning','afternoon'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Light rain football spontaneous game', weather: w('drizzle'), time: ['afternoon','evening'], season: ['monsoon'], region: ['college','any'], dayType: ['any'], vibe: 'move' },
  { text: 'Instant noodles experiment circle', weather: w('drizzle','cloudy'), time: ['evening'], season: ['monsoon'], region: ['college','any'], dayType: ['any'], vibe: 'create' },

  // ── FOGGY (15) ──────────────────────────────────────────────────────────────
  { text: 'Foggy sunrise trek to viewpoint', weather: w('foggy'), time: ['morning'], season: ['winter'], region: ['hills','any'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Bonfire circle in the fog', weather: w('foggy'), time: ['evening','night'], season: ['winter'], region: ['hills','any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Hot thukpa gathering in the hills', weather: w('foggy','rainy'), time: ['evening'], season: ['winter','monsoon'], region: ['hills'], dayType: ['any'], vibe: 'hang' },
  { text: 'Foggy morning chai walk', weather: w('foggy'), time: ['morning'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Momos in the mist gathering', weather: w('foggy','drizzle'), time: ['afternoon','evening'], season: ['winter','monsoon'], region: ['hills','any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Fog photography at dawn', weather: w('foggy'), time: ['morning'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Cozy indoor bakery morning', weather: w('foggy','cloudy'), time: ['morning'], season: ['winter'], region: ['hills','metro','any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Warm wonton soup meet', weather: w('foggy','rainy'), time: ['evening'], season: ['winter'], region: ['hills','any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Fog lights and drive gathering', weather: w('foggy'), time: ['night'], season: ['winter'], region: ['hills','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Candlelit adda on foggy evenings', weather: w('foggy','cloudy'), time: ['evening'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Foggy chai + bhot noodle circle', weather: w('foggy'), time: ['morning','evening'], season: ['winter'], region: ['hills'], dayType: ['any'], vibe: 'hang' },
  { text: 'Story telling with fog outside', weather: w('foggy'), time: ['evening','night'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Slow foggy morning yoga', weather: w('foggy'), time: ['morning'], season: ['winter'], region: ['hills','any'], dayType: ['any'], vibe: 'move' },
  { text: 'Fog watching from the balcony café', weather: w('foggy','cloudy'), time: ['morning'], season: ['winter'], region: ['hills','metro','any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Winter fog + filter coffee adda', weather: w('foggy'), time: ['morning'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },

  // ── THUNDERSTORM (10) ──────────────────────────────────────────────────────
  { text: 'Thunder + board games all evening', weather: w('thunderstorm'), time: ['evening','night'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Storm and movie marathon', weather: w('thunderstorm','rainy'), time: ['evening','night'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Thunderstorm chai + pakora session', weather: w('thunderstorm'), time: ['afternoon','evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Storm horror story circle', weather: w('thunderstorm'), time: ['night'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Heavy rain cooking challenge', weather: w('thunderstorm','rainy'), time: ['afternoon','evening'], season: ['monsoon'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Thunderstorm jam session', weather: w('thunderstorm'), time: ['afternoon','evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Indoor poetry reading during storm', weather: w('thunderstorm','rainy'), time: ['afternoon','evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Storm tracking + hot cocoa session', weather: w('thunderstorm'), time: ['afternoon','evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Chai + thunder + Antakshari', weather: w('thunderstorm','rainy'), time: ['evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Lightning watching from indoors safely', weather: w('thunderstorm'), time: ['evening','night'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },

  // ── MORNING (30) ──────────────────────────────────────────────────────────────
  { text: 'Sunrise yoga circle in the park', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Dawn photography walk', weather: w('sunny','partly_cloudy','foggy'), time: ['morning'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Breakfast paratha session', weather: ANY_W, time: ['morning'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Morning chai at the railway station', weather: ANY_W, time: ['morning'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: '5am trek start gathering', weather: w('sunny','partly_cloudy','foggy'), time: ['morning'], season: ['winter'], region: ['hills','any'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Early swim and chai after', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['summer'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Smoothie bowl brunch run', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['summer'], region: ['metro','college'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Morning temple hop with chai', weather: w('sunny','partly_cloudy','foggy'), time: ['morning'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Dawn cycle ride', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Sunrise beach walk', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['coastal'], dayType: ['any'], vibe: 'move' },
  { text: 'Idli sambar breakfast gathering', weather: ANY_W, time: ['morning'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Morning paper and chai adda', weather: ANY_W, time: ['morning'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'learn' },
  { text: 'Morning gym + juice bar run', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['metro','any'], dayType: ['any'], vibe: 'move' },
  { text: 'Sunrise silent walk', weather: w('sunny','partly_cloudy','foggy'), time: ['morning'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Early morning laughter yoga', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Dawn fish market walk', weather: w('partly_cloudy','cloudy'), time: ['morning'], season: ['any'], region: ['coastal'], dayType: ['any'], vibe: 'explore' },
  { text: 'Oats and options brunch', weather: ANY_W, time: ['morning'], season: ['any'], region: ['metro','college'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Morning book club before work', weather: ANY_W, time: ['morning'], season: ['any'], region: ['metro','any'], dayType: ['weekday'], vibe: 'learn' },
  { text: 'Banana pancake Sunday breakfast', weather: ANY_W, time: ['morning'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Farm fresh breakfast run', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Morning craft session + chai', weather: w('partly_cloudy','cloudy'), time: ['morning'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'First chai of the week adda', weather: ANY_W, time: ['morning'], season: ['any'], region: ['any'], dayType: ['weekday'], vibe: 'hang' },
  { text: 'Breakfast club at the corner dhaba', weather: ANY_W, time: ['morning'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Pre-work walk and talk', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['any'], dayType: ['weekday'], vibe: 'move' },
  { text: 'Morning journaling circle with masala chai', weather: ANY_W, time: ['morning'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Early birder group walk', weather: w('sunny','partly_cloudy','foggy'), time: ['morning'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Morning heritage building walk', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['winter'], region: ['metro','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Sunrise music listening circle', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Chole bhature breakfast run', weather: ANY_W, time: ['morning'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Morning rooftop chai circuit', weather: w('sunny','partly_cloudy','foggy'), time: ['morning'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },

  // ── AFTERNOON (30) ──────────────────────────────────────────────────────────
  { text: 'Post-lunch walk in the colony', weather: w('sunny','partly_cloudy'), time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Chai at 3pm — the golden hour', weather: ANY_W, time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Museum and mango shake afternoon', weather: w('sunny','partly_cloudy'), time: ['afternoon'], season: ['summer'], region: ['metro','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Library meet-and-read session', weather: ANY_W, time: ['afternoon'], season: ['any'], region: ['college','metro','any'], dayType: ['weekday'], vibe: 'learn' },
  { text: 'Laziest Sunday afternoon adda', weather: ANY_W, time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Afternoon book swap session', weather: w('cloudy','drizzle'), time: ['afternoon'], season: ['any'], region: ['college','metro'], dayType: ['weekend'], vibe: 'learn' },
  { text: 'Siesta + chai + adda after', weather: ANY_W, time: ['afternoon'], season: ['summer'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Afternoon cultural talk session', weather: w('cloudy','partly_cloudy'), time: ['afternoon'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'learn' },
  { text: 'Tea garden walk', weather: w('sunny','partly_cloudy'), time: ['afternoon'], season: ['any'], region: ['hills'], dayType: ['any'], vibe: 'explore' },
  { text: 'Mango milkshake binge run', weather: w('sunny','partly_cloudy'), time: ['afternoon'], season: ['summer'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Slow reading under a tree', weather: w('partly_cloudy','cloudy'), time: ['afternoon'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'learn' },
  { text: '3pm nimbu paani and Ludo', weather: w('sunny','partly_cloudy'), time: ['afternoon'], season: ['summer'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Afternoon painting circle', weather: w('cloudy','partly_cloudy'), time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Traditional lunch spot discovery', weather: ANY_W, time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Afternoon jam in the studio', weather: ANY_W, time: ['afternoon'], season: ['any'], region: ['metro','college','any'], dayType: ['any'], vibe: 'create' },
  { text: 'Afternoon mindful walk + chai', weather: w('sunny','partly_cloudy','cloudy'), time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Heritage building photo walk', weather: w('sunny','partly_cloudy','cloudy'), time: ['afternoon'], season: ['winter'], region: ['metro','any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Post-lunch café hop', weather: w('partly_cloudy','cloudy'), time: ['afternoon'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Chaat run at 4pm sharp', weather: w('sunny','partly_cloudy'), time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Sunday afternoon cooking challenge', weather: w('cloudy','rainy'), time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Afternoon mindfulness circle', weather: ANY_W, time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Vintage store Saturday session', weather: w('partly_cloudy','cloudy'), time: ['afternoon'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Lazy river watching together', weather: w('cloudy','drizzle'), time: ['afternoon'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Post-lunch chai + sabudana', weather: ANY_W, time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Sketch swap meetup', weather: w('cloudy','partly_cloudy'), time: ['afternoon'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Plant nursery discovery run', weather: w('sunny','partly_cloudy'), time: ['afternoon'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Afternoon folk music jam', weather: w('partly_cloudy','cloudy'), time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Thali discovery run', weather: ANY_W, time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Afternoon DSLR shoot in the colony', weather: w('partly_cloudy','cloudy'), time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Ice cream crawl in summer', weather: w('sunny','partly_cloudy'), time: ['afternoon'], season: ['summer'], region: ['any'], dayType: ['any'], vibe: 'explore' },

  // ── EVENING (30) ──────────────────────────────────────────────────────────────
  { text: 'Sundowner adda on the rooftop', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['any'], region: ['metro','any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Riverside walk at sunset', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Evening jam under the stars', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Park walk + pakora stop', weather: w('partly_cloudy','cloudy','drizzle'), time: ['evening'], season: ['monsoon','winter'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Bhelpuri + gossip circle', weather: w('partly_cloudy','sunny'), time: ['evening'], season: ['any'], region: ['coastal','metro','any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Jazz and coffee evening', weather: w('cloudy','partly_cloudy'), time: ['evening'], season: ['any'], region: ['metro','any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Evening yoga in the garden', weather: w('partly_cloudy','sunny'), time: ['evening'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Terrace sundowner session', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['winter'], region: ['metro','any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Evening badminton at the ground', weather: w('partly_cloudy','cloudy'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Pani puri crawl at dusk', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Evening singing circle in the park', weather: w('partly_cloudy','sunny'), time: ['evening'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Twilight cycling run', weather: w('partly_cloudy','sunny'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Evening walk to the dargah', weather: w('partly_cloudy','sunny'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Chai tasting evening', weather: w('partly_cloudy','cloudy'), time: ['evening'], season: ['winter'], region: ['hills','any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Karaoke evening at the café', weather: ANY_W, time: ['evening'], season: ['any'], region: ['metro','college','any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Evening folk music listening adda', weather: w('partly_cloudy','cloudy'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Dusk swim + chai after', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['summer'], region: ['coastal','any'], dayType: ['any'], vibe: 'move' },
  { text: 'Rooftop movie with chai', weather: w('partly_cloudy','cloudy'), time: ['evening'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Evening street food walk', weather: w('partly_cloudy','cloudy'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Evening adda at the cutting chai stall', weather: ANY_W, time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Golden hour photography run', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Evening rock climbing session', weather: w('partly_cloudy','cloudy'), time: ['evening'], season: ['winter'], region: ['metro','any'], dayType: ['any'], vibe: 'move' },
  { text: 'Evening walk by the sea', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['any'], region: ['coastal'], dayType: ['any'], vibe: 'move' },
  { text: 'Chai and sunset watching', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Evening book club with wine or chai', weather: w('cloudy','partly_cloudy'), time: ['evening'], season: ['any'], region: ['metro','any'], dayType: ['any'], vibe: 'learn' },
  { text: 'Sunset volleyball game', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['any'], region: ['coastal','any'], dayType: ['any'], vibe: 'move' },
  { text: 'Evening momo run in the hills', weather: w('partly_cloudy','cloudy','foggy'), time: ['evening'], season: ['winter'], region: ['hills'], dayType: ['any'], vibe: 'explore' },
  { text: 'Rooftop guitar circle', weather: w('partly_cloudy','cloudy'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Chai at the station chai stall', weather: ANY_W, time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Evening jam at the amphitheatre', weather: w('partly_cloudy','sunny'), time: ['evening'], season: ['winter'], region: ['metro','any'], dayType: ['weekend'], vibe: 'create' },

  // ── NIGHT (30) ──────────────────────────────────────────────────────────────
  { text: 'Midnight chai run to the all-night stall', weather: ANY_W, time: ['night'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Late-night biryani run', weather: ANY_W, time: ['night'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Night driving playlist swap', weather: ANY_W, time: ['night'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Midnight momo craving run', weather: ANY_W, time: ['night'], season: ['winter'], region: ['hills','any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Stargazing on the terrace', weather: w('sunny','partly_cloudy'), time: ['night'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Late-night board games marathon', weather: ANY_W, time: ['night'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Night market walk', weather: w('partly_cloudy','cloudy','sunny'), time: ['night'], season: ['winter'], region: ['metro','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Overnight trek to sunrise point', weather: w('sunny','partly_cloudy'), time: ['night'], season: ['winter'], region: ['hills','any'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Night jam session', weather: ANY_W, time: ['night'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Late-night dosa run', weather: ANY_W, time: ['night'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Midnight coding + chai circle', weather: ANY_W, time: ['night'], season: ['any'], region: ['college','metro'], dayType: ['any'], vibe: 'learn' },
  { text: 'Night photography walk in the city', weather: w('partly_cloudy','cloudy'), time: ['night'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Late-night debate + snacks', weather: ANY_W, time: ['night'], season: ['any'], region: ['college','any'], dayType: ['any'], vibe: 'learn' },
  { text: 'Night cycling around the city', weather: w('partly_cloudy','cloudy','sunny'), time: ['night'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Late-night chai + existential conversations', weather: ANY_W, time: ['night'], season: ['any'], region: ['college','any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Stargazing + blankets + silence', weather: w('sunny','partly_cloudy'), time: ['night'], season: ['winter'], region: ['hills','any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Night run crew gathering', weather: w('partly_cloudy','cloudy'), time: ['night'], season: ['any'], region: ['metro','any'], dayType: ['any'], vibe: 'move' },
  { text: 'Late-night art session with music', weather: ANY_W, time: ['night'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Night train station walk', weather: w('partly_cloudy','cloudy'), time: ['night'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Post-midnight maggi and chai', weather: ANY_W, time: ['night'], season: ['any'], region: ['college','any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Night time raga listening session', weather: ANY_W, time: ['night'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Moonrise watching gathering', weather: w('sunny','partly_cloudy'), time: ['night'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Midnight chai + journal swap', weather: ANY_W, time: ['night'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Night walk to the oldest part of the city', weather: w('partly_cloudy','cloudy'), time: ['night'], season: ['winter'], region: ['metro','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Night karaoke at someone’s terrace', weather: w('partly_cloudy','sunny'), time: ['night'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Midnight skin of the teeth gaming session', weather: ANY_W, time: ['night'], season: ['any'], region: ['college','any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Night time card games circle', weather: ANY_W, time: ['night'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Late-night open mic performance prep', weather: ANY_W, time: ['night'], season: ['any'], region: ['college','metro'], dayType: ['any'], vibe: 'create' },
  { text: 'Overnight tarot and conversation circle', weather: ANY_W, time: ['night'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Night food truck circuit', weather: w('partly_cloudy','cloudy'), time: ['night'], season: ['winter'], region: ['metro','any'], dayType: ['weekend'], vibe: 'explore' },

  // ── HILLS (30) ──────────────────────────────────────────────────────────────
  { text: 'Momo adda in the mist', weather: w('foggy','drizzle','cloudy'), time: ['afternoon','evening'], season: ['winter','monsoon'], region: ['hills'], dayType: ['any'], vibe: 'hang' },
  { text: 'Bonfire circle with thukpa', weather: w('foggy','cloudy','rainy'), time: ['evening','night'], season: ['winter'], region: ['hills'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Sunrise trek with maggi stop', weather: w('sunny','partly_cloudy','foggy'), time: ['morning'], season: ['any'], region: ['hills'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Rhododendron trail walk', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['summer','winter'], region: ['hills'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Valley viewpoint hang', weather: w('sunny','partly_cloudy','foggy'), time: ['morning','afternoon','evening'], season: ['any'], region: ['hills'], dayType: ['any'], vibe: 'hang' },
  { text: 'Chopper chai at the hilltop', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['any'], region: ['hills'], dayType: ['any'], vibe: 'explore' },
  { text: 'Waterfall photowalk', weather: w('sunny','partly_cloudy','drizzle'), time: ['morning','afternoon'], season: ['monsoon','summer'], region: ['hills'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Monastery hop with local guide', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['any'], region: ['hills'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Ridge walk at golden hour', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['any'], region: ['hills'], dayType: ['any'], vibe: 'move' },
  { text: 'Forest bathing circle', weather: w('partly_cloudy','cloudy','drizzle'), time: ['morning','afternoon'], season: ['any'], region: ['hills'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Hot soup adda at the viewpoint café', weather: w('foggy','cloudy','rainy'), time: ['afternoon','evening'], season: ['winter','monsoon'], region: ['hills'], dayType: ['any'], vibe: 'hang' },
  { text: 'Cycling on mountain roads', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['summer','winter'], region: ['hills'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Night sky watch with telescope', weather: w('sunny','partly_cloudy'), time: ['night'], season: ['winter'], region: ['hills'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Homestay cooking session', weather: w('cloudy','rainy','foggy'), time: ['afternoon'], season: ['any'], region: ['hills'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Moonrise from the hilltop', weather: w('sunny','partly_cloudy'), time: ['night'], season: ['any'], region: ['hills'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Pine forest walk and picnic', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['winter','summer'], region: ['hills'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Darjeeling tea tasting session', weather: w('foggy','cloudy','partly_cloudy'), time: ['morning','afternoon'], season: ['any'], region: ['hills'], dayType: ['any'], vibe: 'explore' },
  { text: 'Valley mist photography at dawn', weather: w('foggy'), time: ['morning'], season: ['winter','monsoon'], region: ['hills'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Local folk music evening', weather: w('cloudy','foggy'), time: ['evening'], season: ['winter'], region: ['hills'], dayType: ['any'], vibe: 'hang' },
  { text: 'Firefly walk in monsoon', weather: w('drizzle','partly_cloudy'), time: ['evening','night'], season: ['monsoon'], region: ['hills'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Hot Tibetan bread gathering', weather: w('foggy','cloudy','rainy'), time: ['morning'], season: ['winter'], region: ['hills'], dayType: ['any'], vibe: 'hang' },
  { text: 'Mountain birds guided walk', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['hills'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Snow point photography sprint', weather: w('snow','foggy'), time: ['morning','afternoon'], season: ['winter'], region: ['hills'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Trekking bootcamp with snacks', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['winter','summer'], region: ['hills'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Dawn prayer at the monastery', weather: w('foggy','partly_cloudy'), time: ['morning'], season: ['any'], region: ['hills'], dayType: ['any'], vibe: 'explore' },
  { text: 'Cloud forest silent walk', weather: w('foggy','drizzle'), time: ['morning','afternoon'], season: ['monsoon'], region: ['hills'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Night bonfire with guitar', weather: w('partly_cloudy','cloudy'), time: ['night'], season: ['winter'], region: ['hills'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Local market morning haggling walk', weather: w('partly_cloudy','foggy'), time: ['morning'], season: ['any'], region: ['hills'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Hot wai wai noodle soup together', weather: w('foggy','rainy','cloudy'), time: ['evening'], season: ['winter','monsoon'], region: ['hills'], dayType: ['any'], vibe: 'hang' },
  { text: 'Viewpoint sunrise + chai ritual', weather: w('sunny','partly_cloudy','foggy'), time: ['morning'], season: ['any'], region: ['hills'], dayType: ['weekend'], vibe: 'explore' },

  // ── METRO (30) ──────────────────────────────────────────────────────────────
  { text: 'Indie band at the rooftop bar', weather: w('partly_cloudy','cloudy'), time: ['evening','night'], season: ['winter'], region: ['metro'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Gallery hop in the art district', weather: w('partly_cloudy','cloudy'), time: ['afternoon'], season: ['any'], region: ['metro'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Specialty coffee adda in the neighbourhood', weather: w('partly_cloudy','cloudy'), time: ['morning','afternoon'], season: ['any'], region: ['metro'], dayType: ['any'], vibe: 'hang' },
  { text: 'Thrift shopping Saturday run', weather: w('partly_cloudy','sunny'), time: ['afternoon'], season: ['any'], region: ['metro'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Craft brewery visit with crew', weather: w('partly_cloudy','cloudy'), time: ['afternoon','evening'], season: ['winter'], region: ['metro'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Connaught Place chai crawl', weather: w('sunny','partly_cloudy'), time: ['afternoon','evening'], season: ['winter'], region: ['metro'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Book launch + wine social', weather: w('partly_cloudy','cloudy'), time: ['evening'], season: ['any'], region: ['metro'], dayType: ['weekday'], vibe: 'learn' },
  { text: 'Comedy open mic night', weather: ANY_W, time: ['evening','night'], season: ['any'], region: ['metro'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Farmers market + brunch', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['metro'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Food festival circuit', weather: w('partly_cloudy','sunny'), time: ['afternoon','evening'], season: ['winter'], region: ['metro'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Museum and lunch combo', weather: w('partly_cloudy','cloudy'), time: ['afternoon'], season: ['any'], region: ['metro'], dayType: ['weekend'], vibe: 'learn' },
  { text: 'Film festival screening + discussion', weather: ANY_W, time: ['evening'], season: ['any'], region: ['metro'], dayType: ['weekend'], vibe: 'learn' },
  { text: 'Poetry slam evening', weather: ANY_W, time: ['evening'], season: ['any'], region: ['metro'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Late-night paan run', weather: ANY_W, time: ['night'], season: ['any'], region: ['metro'], dayType: ['any'], vibe: 'explore' },
  { text: 'Rooftop lounge sunset session', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['winter'], region: ['metro'], dayType: ['any'], vibe: 'hang' },
  { text: 'Cycle tour of the old city', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['winter'], region: ['metro'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Indie gig at the basement venue', weather: ANY_W, time: ['evening','night'], season: ['any'], region: ['metro'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Art exhibition and conversation', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['metro'], dayType: ['weekend'], vibe: 'learn' },
  { text: 'Metro photowalk with cameras', weather: w('partly_cloudy','cloudy'), time: ['afternoon'], season: ['winter'], region: ['metro'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Popup restaurant trial run', weather: w('partly_cloudy','cloudy'), time: ['afternoon','evening'], season: ['any'], region: ['metro'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Ghost walk in the old city', weather: w('cloudy','foggy'), time: ['evening','night'], season: ['winter'], region: ['metro'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Jazz evening at the intimate café', weather: w('cloudy','partly_cloudy'), time: ['evening'], season: ['any'], region: ['metro'], dayType: ['any'], vibe: 'hang' },
  { text: 'Weekend dim sum feast', weather: ANY_W, time: ['morning','afternoon'], season: ['any'], region: ['metro'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Street art Instagram walk', weather: w('partly_cloudy','sunny'), time: ['afternoon'], season: ['any'], region: ['metro'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Night market in the flea zone', weather: w('partly_cloudy','cloudy'), time: ['evening','night'], season: ['winter'], region: ['metro'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Speakeasy cocktail discovery', weather: ANY_W, time: ['evening','night'], season: ['any'], region: ['metro'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Late-night club sandwich run', weather: ANY_W, time: ['night'], season: ['any'], region: ['metro'], dayType: ['any'], vibe: 'explore' },
  { text: 'Café-hopping in the indie neighbourhood', weather: w('partly_cloudy','cloudy'), time: ['afternoon'], season: ['any'], region: ['metro'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Vintage flea market Sunday', weather: w('partly_cloudy','sunny'), time: ['morning','afternoon'], season: ['winter'], region: ['metro'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Rooftop brunch with city view', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['winter'], region: ['metro'], dayType: ['weekend'], vibe: 'hang' },

  // ── COASTAL (30) ──────────────────────────────────────────────────────────────
  { text: 'Beach walk at sunrise', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['coastal'], dayType: ['any'], vibe: 'move' },
  { text: 'Seafood discovery run', weather: w('sunny','partly_cloudy'), time: ['afternoon'], season: ['any'], region: ['coastal'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Coconut water and cards at the shack', weather: w('sunny','partly_cloudy'), time: ['afternoon'], season: ['summer'], region: ['coastal'], dayType: ['any'], vibe: 'hang' },
  { text: 'Early morning fishing watch', weather: w('partly_cloudy','cloudy'), time: ['morning'], season: ['any'], region: ['coastal'], dayType: ['any'], vibe: 'explore' },
  { text: 'Beach volleyball spontaneous game', weather: w('sunny','partly_cloudy'), time: ['afternoon','evening'], season: ['any'], region: ['coastal'], dayType: ['any'], vibe: 'move' },
  { text: 'Beach clean-up + chai', weather: w('partly_cloudy','sunny'), time: ['morning'], season: ['any'], region: ['coastal'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Sea breeze reading circle', weather: w('sunny','partly_cloudy','windy'), time: ['morning','afternoon'], season: ['any'], region: ['coastal'], dayType: ['any'], vibe: 'learn' },
  { text: 'Surf lesson gathering', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['summer'], region: ['coastal'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Shoreline run at low tide', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['coastal'], dayType: ['any'], vibe: 'move' },
  { text: 'Night beach bonfire', weather: w('partly_cloudy','cloudy'), time: ['night'], season: ['winter'], region: ['coastal'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Backwater boat gathering', weather: w('sunny','partly_cloudy'), time: ['afternoon'], season: ['any'], region: ['coastal'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Beach photography at magic hour', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['any'], region: ['coastal'], dayType: ['any'], vibe: 'create' },
  { text: 'Seafood shack crawl', weather: w('partly_cloudy','cloudy'), time: ['afternoon','evening'], season: ['any'], region: ['coastal'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Beach yoga at dawn', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['coastal'], dayType: ['any'], vibe: 'move' },
  { text: 'Rock pool exploration walk', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['winter','summer'], region: ['coastal'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Sunset sailing adventure', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['any'], region: ['coastal'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Coconut grove walk', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['any'], region: ['coastal'], dayType: ['any'], vibe: 'move' },
  { text: 'Beachside music jam', weather: w('partly_cloudy','sunny'), time: ['evening'], season: ['winter'], region: ['coastal'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Marine drive stroll at midnight', weather: w('partly_cloudy','cloudy'), time: ['night'], season: ['any'], region: ['coastal'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Promenade chai walk', weather: w('partly_cloudy','cloudy','windy'), time: ['evening'], season: ['any'], region: ['coastal'], dayType: ['any'], vibe: 'move' },
  { text: 'Night beach cricket', weather: w('partly_cloudy','sunny'), time: ['night'], season: ['winter'], region: ['coastal'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Beach Frisbee + sunset', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['any'], region: ['coastal'], dayType: ['any'], vibe: 'move' },
  { text: 'Coastal cycling trail', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['winter'], region: ['coastal'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Beachside book club', weather: w('partly_cloudy','sunny'), time: ['afternoon'], season: ['any'], region: ['coastal'], dayType: ['weekend'], vibe: 'learn' },
  { text: 'Overnight beach camping', weather: w('partly_cloudy','sunny'), time: ['night'], season: ['winter'], region: ['coastal'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Lighthouse visit and history talk', weather: w('sunny','partly_cloudy'), time: ['afternoon'], season: ['any'], region: ['coastal'], dayType: ['weekend'], vibe: 'learn' },
  { text: 'Snorkeling first-timers circle', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['summer'], region: ['coastal'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Sea cave walk at low tide', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['winter','summer'], region: ['coastal'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Sunset at the beach with chai', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['any'], region: ['coastal'], dayType: ['any'], vibe: 'hang' },
  { text: 'Night firefly kayak session', weather: w('partly_cloudy'), time: ['night'], season: ['monsoon'], region: ['coastal'], dayType: ['weekend'], vibe: 'explore' },

  // ── COLLEGE (30) ──────────────────────────────────────────────────────────────
  { text: 'Canteen chai + chai + chai', weather: ANY_W, time: ['morning','afternoon','evening'], season: ['any'], region: ['college'], dayType: ['weekday'], vibe: 'hang' },
  { text: 'Library midnight study circle', weather: ANY_W, time: ['night'], season: ['any'], region: ['college'], dayType: ['weekday'], vibe: 'learn' },
  { text: 'Hostel rooftop jam', weather: w('partly_cloudy','sunny'), time: ['evening','night'], season: ['any'], region: ['college'], dayType: ['any'], vibe: 'create' },
  { text: 'Paratha run at the dhaba', weather: ANY_W, time: ['morning','night'], season: ['any'], region: ['college'], dayType: ['any'], vibe: 'explore' },
  { text: 'Music room practice session', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['college'], dayType: ['any'], vibe: 'create' },
  { text: 'Night cycling around campus', weather: w('partly_cloudy','cloudy'), time: ['night'], season: ['any'], region: ['college'], dayType: ['any'], vibe: 'move' },
  { text: 'Ground cricket with semester tension', weather: w('sunny','partly_cloudy'), time: ['afternoon','evening'], season: ['any'], region: ['college'], dayType: ['any'], vibe: 'move' },
  { text: 'Maggi at the hostel room together', weather: ANY_W, time: ['night'], season: ['any'], region: ['college'], dayType: ['any'], vibe: 'hang' },
  { text: 'Exam season chai circle', weather: ANY_W, time: ['night','morning'], season: ['any'], region: ['college'], dayType: ['weekday'], vibe: 'hang' },
  { text: 'Pre-exam ghost story circle', weather: w('rainy','cloudy'), time: ['night'], season: ['any'], region: ['college'], dayType: ['weekday'], vibe: 'hang' },
  { text: 'Campus photography walk', weather: w('sunny','partly_cloudy'), time: ['afternoon'], season: ['any'], region: ['college'], dayType: ['any'], vibe: 'create' },
  { text: 'Ground badminton late evening', weather: w('partly_cloudy','cloudy'), time: ['evening'], season: ['any'], region: ['college'], dayType: ['any'], vibe: 'move' },
  { text: 'Hostel room movie night', weather: ANY_W, time: ['night'], season: ['any'], region: ['college'], dayType: ['any'], vibe: 'hang' },
  { text: 'End-of-semester potluck', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['college'], dayType: ['any'], vibe: 'hang' },
  { text: 'Cultural fest prep rehearsal', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['college'], dayType: ['any'], vibe: 'create' },
  { text: 'Night study group with snacks', weather: ANY_W, time: ['night'], season: ['any'], region: ['college'], dayType: ['weekday'], vibe: 'learn' },
  { text: 'Chai and complaints circle', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['college'], dayType: ['any'], vibe: 'hang' },
  { text: 'Sunday campus birding walk', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['college'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Hostel room guitar session', weather: ANY_W, time: ['evening','night'], season: ['any'], region: ['college'], dayType: ['any'], vibe: 'create' },
  { text: 'Group presentation practice night', weather: ANY_W, time: ['night'], season: ['any'], region: ['college'], dayType: ['weekday'], vibe: 'learn' },
  { text: 'College adda post internship', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['college'], dayType: ['any'], vibe: 'hang' },
  { text: 'Monsoon ground cricket', weather: w('drizzle','partly_cloudy'), time: ['afternoon'], season: ['monsoon'], region: ['college'], dayType: ['any'], vibe: 'move' },
  { text: 'Campus café new menu discovery', weather: ANY_W, time: ['afternoon'], season: ['any'], region: ['college'], dayType: ['any'], vibe: 'explore' },
  { text: 'Doubt clearing adda with chai', weather: ANY_W, time: ['afternoon','night'], season: ['any'], region: ['college'], dayType: ['weekday'], vibe: 'learn' },
  { text: 'Sports meet warm-up gathering', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['college'], dayType: ['any'], vibe: 'move' },
  { text: 'Farewell chai with batchmates', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['college'], dayType: ['any'], vibe: 'hang' },
  { text: 'Campus open mic night', weather: ANY_W, time: ['evening','night'], season: ['any'], region: ['college'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Mess food survival gathering', weather: ANY_W, time: ['afternoon'], season: ['any'], region: ['college'], dayType: ['weekday'], vibe: 'hang' },
  { text: 'Fresher welcome adda', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['college'], dayType: ['any'], vibe: 'hang' },
  { text: 'Semester-end road trip planning circle', weather: ANY_W, time: ['night'], season: ['any'], region: ['college'], dayType: ['any'], vibe: 'explore' },

  // ── DIWALI (10) ──────────────────────────────────────────────────────────────
  { text: 'Rangoli making circle', weather: w('sunny','partly_cloudy'), time: ['afternoon','evening'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Diya lighting and chai gathering', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Lantern walk on Diwali eve', weather: w('partly_cloudy','sunny'), time: ['evening'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Mithai swap circle', weather: ANY_W, time: ['afternoon','evening'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Kali Puja night adda', weather: w('partly_cloudy','cloudy'), time: ['night'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Firecracker-free Diwali party', weather: w('partly_cloudy','sunny'), time: ['evening'], season: ['winter'], region: ['metro','college','any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Diwali recipe potluck', weather: ANY_W, time: ['afternoon'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Bhai dooj breakfast adda', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Diwali lights photography walk', weather: w('partly_cloudy','cloudy'), time: ['evening','night'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Diyas and dance on the rooftop', weather: w('partly_cloudy','sunny'), time: ['evening'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },

  // ── HOLI (8) ──────────────────────────────────────────────────────────────
  { text: 'Holi rang session with thandai', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['summer'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Thandai tasting circle', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['summer'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Post-Holi dahi bhalla binge', weather: w('sunny','partly_cloudy'), time: ['afternoon'], season: ['summer'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Dry Holi with gulal only', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['summer'], region: ['metro','college','any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Holi DJ night on the terrace', weather: w('partly_cloudy','cloudy'), time: ['evening','night'], season: ['summer'], region: ['metro','any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Color run prep session', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['summer'], region: ['metro','college','any'], dayType: ['any'], vibe: 'move' },
  { text: 'Holi breakfast gathering', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['summer'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Colour jamming session', weather: w('sunny','partly_cloudy'), time: ['afternoon'], season: ['summer'], region: ['any'], dayType: ['any'], vibe: 'create' },

  // ── DURGA PUJA (8) ──────────────────────────────────────────────────────────
  { text: 'Pandal hop with bhog', weather: w('partly_cloudy','cloudy'), time: ['evening'], season: ['monsoon','winter'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Ashtami bhog gathering', weather: w('partly_cloudy','cloudy'), time: ['afternoon'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Dhak music walk in the evening', weather: w('partly_cloudy','cloudy'), time: ['evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Puja bhog potluck', weather: ANY_W, time: ['afternoon'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Mahalaya moonrise watch', weather: w('partly_cloudy','cloudy'), time: ['night'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'New clothes + pandal selfie run', weather: w('partly_cloudy','sunny'), time: ['evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Evening light and decoration walk', weather: w('partly_cloudy','cloudy'), time: ['evening'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Sindoor khela after Dashami', weather: w('partly_cloudy','cloudy'), time: ['afternoon'], season: ['monsoon'], region: ['any'], dayType: ['any'], vibe: 'hang' },

  // ── CHRISTMAS (6) ──────────────────────────────────────────────────────────
  { text: 'Midnight mass + hot chocolate', weather: w('foggy','cloudy'), time: ['night'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Cake exchange Sunday', weather: ANY_W, time: ['afternoon'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Carol singing circle', weather: w('foggy','cloudy','partly_cloudy'), time: ['evening'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Christmas trivia night', weather: ANY_W, time: ['evening','night'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Plum cake tasting session', weather: ANY_W, time: ['afternoon'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Christmas lights walk in the city', weather: w('foggy','cloudy','partly_cloudy'), time: ['evening','night'], season: ['winter'], region: ['metro','any'], dayType: ['any'], vibe: 'explore' },

  // ── EID (6) ──────────────────────────────────────────────────────────────
  { text: 'Sheer khurma adda', weather: ANY_W, time: ['morning'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Biryani potluck gathering', weather: ANY_W, time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Eid ki shaam chai circle', weather: w('partly_cloudy','sunny'), time: ['evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Seviyan making together', weather: ANY_W, time: ['morning'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Eid market walk and snack run', weather: w('sunny','partly_cloudy'), time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Post-namaaz biryani feast', weather: ANY_W, time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },

  // ── NEW YEAR (6) ──────────────────────────────────────────────────────────
  { text: 'Countdown rooftop party', weather: w('partly_cloudy','cloudy'), time: ['night'], season: ['winter'], region: ['metro','any'], dayType: ['any'], vibe: 'hang' },
  { text: 'New Year day brunch', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Midnight fireworks watch', weather: w('partly_cloudy','cloudy'), time: ['night'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'First day sunrise watch together', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'New Year resolution + chai adda', weather: ANY_W, time: ['morning'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Annual year-end stories circle', weather: ANY_W, time: ['evening','night'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },

  // ── INDEPENDENCE / REPUBLIC DAY (6) ────────────────────────────────────────
  { text: 'Kite flying on the terrace', weather: w('sunny','windy','partly_cloudy'), time: ['morning','afternoon'], season: ['summer','winter'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Tricolor walk at sunrise', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['summer','winter'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Flag-themed chai gathering', weather: ANY_W, time: ['morning'], season: ['summer','winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Republic Day parade watch party', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['winter'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'National anthem singing circle', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['summer','winter'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Freedom run at 7am', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['summer','winter'], region: ['any'], dayType: ['any'], vibe: 'move' },

  // ── WEEKEND ENERGY (30) ──────────────────────────────────────────────────────
  { text: 'Late brunch because we deserve it', weather: ANY_W, time: ['morning'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Sunday drive with no destination', weather: w('sunny','partly_cloudy'), time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Saturday morning slow walk', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Lazy Saturday movie marathon', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Weekend barbecue at home', weather: w('sunny','partly_cloudy'), time: ['evening'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Sunday farmers market + brunch', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Long table lunch gathering', weather: ANY_W, time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Road trip to the nearest viewpoint', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Day hike + dabba lunch', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['winter','summer'], region: ['hills','any'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Saturday art class + gallery visit', weather: w('partly_cloudy','cloudy'), time: ['afternoon'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Weekend karaoke house party', weather: ANY_W, time: ['evening','night'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Sunday game night marathon', weather: ANY_W, time: ['evening','night'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Sleepover planning session', weather: ANY_W, time: ['evening','night'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Saturday late night adda', weather: ANY_W, time: ['night'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Weekend binge fest with crew', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Long walk to somewhere new', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Biryani Sunday cooking session', weather: ANY_W, time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Weekend antakshari championship', weather: ANY_W, time: ['evening'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Brunch that stretches into dinner', weather: ANY_W, time: ['morning'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Lazy Sunday hammock hang', weather: w('sunny','partly_cloudy'), time: ['afternoon'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Weekend chai tasting trail', weather: ANY_W, time: ['afternoon'], season: ['any'], region: ['hills','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Saturday live music venue hop', weather: ANY_W, time: ['evening'], season: ['any'], region: ['metro','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Weekend photography challenge', weather: w('sunny','partly_cloudy'), time: ['morning','afternoon'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Road trip + dhaba stop', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Weekend waterfall trek', weather: w('partly_cloudy','drizzle'), time: ['morning'], season: ['monsoon','summer'], region: ['hills','any'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Saturday night rooftop bonfire', weather: w('partly_cloudy','cloudy'), time: ['night'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Sunday cycling + lunch', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'move' },
  { text: 'Weekend sketch crawl in the city', weather: w('partly_cloudy','sunny'), time: ['morning','afternoon'], season: ['winter'], region: ['metro','any'], dayType: ['weekend'], vibe: 'create' },
  { text: 'Sunday vintage flea market', weather: w('sunny','partly_cloudy'), time: ['morning'], season: ['winter'], region: ['metro','any'], dayType: ['weekend'], vibe: 'explore' },
  { text: 'Weekend bonfire + cooking', weather: w('partly_cloudy','cloudy'), time: ['evening'], season: ['winter'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },

  // ── UNIVERSAL FALLBACKS (20) ──────────────────────────────────────────────────
  { text: 'Coffee meetup at the usual place', weather: ANY_W, time: ['morning','afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Quick walk — let’s go', weather: ANY_W, time: ['morning','afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Chai and conversation, no agenda', weather: ANY_W, time: ['morning','afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Sunday brunch run', weather: ANY_W, time: ['morning'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'hang' },
  { text: 'Jam session — anyone play anything', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Board game evening', weather: ANY_W, time: ['evening','night'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Something fun, TBD, let’s just go', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Movie at someone’s place', weather: ANY_W, time: ['evening','night'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Chai adda — show up, we’ll figure it out', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Run + breakfast after', weather: ANY_W, time: ['morning'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Study + snacks + good music', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'learn' },
  { text: 'Cook something together', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'create' },
  { text: 'Walk and talk session', weather: ANY_W, time: ['morning','afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'move' },
  { text: 'Potluck at someone’s place', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Something local, something good', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'explore' },
  { text: 'Snack run + no-plan afternoon', weather: ANY_W, time: ['afternoon'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Outdoor hang before it gets dark', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Music listening session', weather: ANY_W, time: ['afternoon','evening','night'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Freestyle gathering — your call', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['any'], vibe: 'hang' },
  { text: 'Everyone bring one dish, one song', weather: ANY_W, time: ['afternoon','evening'], season: ['any'], region: ['any'], dayType: ['weekend'], vibe: 'create' },
]
